version: 2.1

orbs:
  node: circleci/node@5

jobs:

# Installation des dépendances
  build:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm

# Analyse de code
  lint:
    executor: node/default
    steps:
      - checkout
      - run: npm run lint

# Tests unitaires
  test-unit:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run: npm run test:unit

# Tests d'intégration
  test-integration:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run: npm run test:integration

# Déploiement sur l'environnement de développement
  deploy-dev:
    executor: node/default
    steps:
      - checkout
      - run: echo "Déploiement sur l'environnement de développement..."

# Déploiement sur l'environnement d'intégration
  deploy-integration:
    executor: node/default
    steps:
      - checkout
      - run: echo "Déploiement sur l'environnement d'intégration..."

# Déploiement sur l'environnement de production
  deploy-prod:
    executor: node/default
    steps:
      - checkout
      - run: echo "Déploiement sur l'environnement de production..."

workflows:

# Build, tests et déploiement sur l'environnement de développement
  build-test-deploy-dev:
    jobs:
      - build
      - lint:
          requires:
            - build
      - test-unit:
          requires:
            - build
      - test-integration:
          requires:
            - build
      - deploy-dev:
          requires:
            - test-integration
          filters:
            branches:
              only:
                - develop

# Build, tests et déploiement sur l'environnement d'intégration
  build-test-deploy-integration:
    jobs:
      - build
      - lint:
          requires:
            - build
      - test-unit:
          requires:
            - build
      - test-integration:
          requires:
            - build
      - deploy-integration:
          requires:
            - test-integration
          filters:
            branches:
              only:
                - integration

# Build, tests et déploiement sur l'environnement de production
  build-test-deploy-prod:
    jobs:
      - build
      - lint:
          requires:
            - build
      - test-unit:
          requires:
            - build
      - test-integration:
          requires:
            - build
      - deploy-prod:
          requires:
            - test-integration
          filters:
            branches:
              only:
                - main

filters:

# Exclusion des branches "feature" et "hotfix"
  exclude-feature-hotfix:
    branches:
      ignore:
        - /^feature.*/
        - /^hotfix.*/

