# Configuration du fichier .circleci/config.yml

version: 2.1

# Définition des Orbs requis
orbs:
  node: circleci/node@5

# Définition des différents jobs
jobs:
  # Installation des dépendances
  installation_dependances:
    executor: node/default
    steps:
      - checkout
      - run: echo "installation des dépendances..."

  # Analyse du code
  analyse_code:
    executor: node/default
    steps:
      - checkout
      - run: echo "analyse du code..."

  # Nettoyage et empaquetage
  nettoyage_empaquetage:
    executor: node/default
    steps:
      - checkout
      - run: echo "nettoyage et empaquetage..."

  # Tests unitaires
  tests_unitaires:
    executor: node/default
    steps:
      - checkout
      - run: echo "exécution des tests unitaires..."

  # Tests d'intégration
  tests_integration:
    executor: node/default
    steps:
      - checkout
      - run: echo "exécution des tests d'intégration..."

  # Tests de régression
  tests_regression:
    executor: node/default
    steps:
      - checkout
      - run: echo "exécution des tests de régression..."

  # Tests de performance
  tests_performance:
    executor: node/default
    steps:
      - checkout
      - run: echo "exécution des tests de performance..."

  # Tests de sécurité
  tests_securite:
    executor: node/default
    steps:
      - checkout
      - run: echo "exécution des tests de sécurité..."

  # Tests d'accessibilité
  tests_accessibilite:
    executor: node/default
    steps:
      - checkout
      - run: echo "exécution des tests d'accessibilité..."

  # Préparation de l'environnement de déploiement
  preparation_deployment:
    executor: node/default
    steps:
      - checkout
      - run: echo "préparation de l'environnement de déploiement..."

  # Déploiement de l'application
  deployment_application:
    executor: node/default
    steps:
      - checkout
      - run: echo "déploiement de l'application..."

  # Tests de vérification
  tests_verification:
    executor: node/default
    steps:
      - checkout
      - run: echo "exécution des tests de vérification..."

  # Tests de validation fonctionnelle
  tests_validation_fonctionnelle:
    executor: node/default
    steps:
      - checkout
      - run: echo "exécution des tests de validation fonctionnelle..."

  # Tests de charge
  tests_charge:
    executor: node/default
    steps:
      - checkout
      - run: echo "exécution des tests de charge..."

  # Déploiement sur l'environnement de développement
  deployment_dev:
    executor: node/default
    steps:
      - checkout
      - run: echo "déploiement sur l'environnement de développement..."

  # Déploiement sur l'environnement de production
  deployment_prod:
    executor: node/default
    steps:
      - checkout
      - run: echo "déploiement sur l'environnement de production..."

  # Déploiement sur l'environnement de release
  deployment_release:
    executor: node/default
    steps:
      - checkout
      - run: echo "déploiement sur l'environnement de release..."

  # Surveillance et suivi
  surveillance:
    executor: node/default
    steps:
      - checkout
      - run: echo "surveillance..."

###################################################################
# Définition des workflows
workflows:
  version: 2
  build-test-deploy:
    jobs:
      # Exécution des étapes dans l'ordre spécifié
      - installation_dependances
      - analyse_code
      - nettoyage_empaquetage
      - tests_unitaires:
          requires:
            - installation_dependances
            - analyse_code
            - nettoyage_empaquetage
      - tests_integration:
          requires:
            - installation_dependances
            - analyse_code
            - nettoyage_empaquetage
          filters:
            branches:
              ignore:
                - /^feature\/.*$/
                - /^hotfix\/.*$/

      - tests_regression:
          requires:
            - installation_dependances
            - analyse_code
            - nettoyage_empaquetage
          filters:
            branches:
              ignore:
                - /^feature\/.*$/
                - /^hotfix\/.*$/

      - tests_performance:
          requires:
            - installation_dependances
            - analyse_code
            - nettoyage_empaquetage
          filters:
            branches:
              ignore:
                - /^feature\/.*$/
                - /^hotfix\/.*$/

      - tests_securite:
          requires:
            - installation_dependances
            - analyse_code
            - nettoyage_empaquetage

      - tests_accessibilite:
          requires:
            - installation_dependances
            - analyse_code
            - nettoyage_empaquetage
          filters:
            branches:
              only:
                - master

      - preparation_deployment:
          requires:
            - tests_unitaires
            - tests_integration
            - tests_regression
            - tests_performance
            - tests_securite
            - tests_accessibilite
          filters:
            branches:
              ignore:
                - /^feature\/.*$/
                - /^hotfix\/.*$/

      - deployment_application:
          requires:
            - tests_unitaires
            - tests_integration
            - tests_regression
            - tests_performance
            - tests_securite
            - tests_accessibilite
          filters:
            branches:
              ignore:
                - /^feature\/.*$/
                - /^hotfix\/.*$/

      - tests_verification:
          requires:
            - tests_unitaires
            - tests_integration
            - tests_regression
            - tests_performance
            - tests_securite
            - tests_accessibilite
          filters:
            branches:
              ignore:
                - /^feature\/.*$/
                - /^hotfix\/.*$/

      - tests_validation_fonctionnelle:
          requires:
            - tests_unitaires
            - tests_integration
            - tests_regression
            - tests_performance
            - tests_securite
            - tests_accessibilite
          filters:
            branches:
              ignore:
                - /^feature\/.*$/
                - /^hotfix\/.*$/

      - tests_charge:
          requires:
            - tests_unitaires
            - tests_integration
            - tests_regression
            - tests_performance
            - tests_securite
            - tests_accessibilite
          filters:
            branches:
              ignore:
                - /^feature\/.*$/
                - /^hotfix\/.*$/

      - deployment_dev:
          requires:
            - tests_unitaires
            - tests_integration
            - tests_regression
            - tests_performance
            - tests_securite
            - tests_accessibilite
          filters:
            branches:
              only:
                - develop

      - deployment_prod:
          requires:
            - tests_unitaires
            - tests_integration
            - tests_regression
            - tests_performance
            - tests_securite
            - tests_accessibilite
          filters:
            branches:
              only:
                - master

      - deployment_release:
          requires:
            - tests_unitaires
            - tests_integration
            - tests_regression
            - tests_performance
            - tests_securite
            - tests_accessibilite
          filters:
            branches:
              only:
                - /^release\/.*$/

      - surveillance:
          requires:
            - tests_unitaires
            - tests_integration
            - tests_regression
            - tests_performance
            - tests_securite
            - tests_accessibilite
          filters:
            branches:
              ignore:
                - /^feature\/.*$/
                - /^hotfix\/.*$/
