# Configuration du fichier .circleci/config.yml

version: 2.1

# Définition des Orbs nécessaires
orbs:
  node: circleci/node@5

# Définition des différents jobs
jobs:
  # Installation des dépendances
  dependencies_install:
    executor: node/default
    steps:
      - checkout
      - run: echo "Installing dependencies..."

  # Analyse du code
  code_analysis:
    executor: node/default
    steps:
      - checkout
      - run: echo "Performing code analysis..."

  # Nettoyage et packaging
  cleaning_packaging:
    executor: node/default
    steps:
      - checkout
      - run: echo "Cleaning and packaging..."

  # Tests unitaires
  unit_tests:
    executor: node/default
    steps:
      - checkout
      - run: echo "Running unit tests..."

  # Tests d'intégration
  integration_tests:
    executor: node/default
    steps:
      - checkout
      - run: echo "Running integration tests..."

  # Tests de régression
  regression_tests:
    executor: node/default
    steps:
      - checkout
      - run: echo "Running regression tests..."

  # Tests de performance
  performance_tests:
    executor: node/default
    steps:
      - checkout
      - run: echo "Running performance tests..."

  # Tests de sécurité
  security_tests:
    executor: node/default
    steps:
      - checkout
      - run: echo "Running security tests..."

  # Tests d'accessibilité
  access_tests:
    executor: node/default
    steps:
      - checkout
      - run: echo "Running accessibility tests..."

  # Préparation de l'environnement de déploiement
  preparing_deploying_environment:
    executor: node/default
    steps:
      - checkout
      - run: echo "Preparing deployment environment..."

  # Déploiement de l'application
  application_deployment:
    executor: node/default
    steps:
      - checkout
      - run: echo "Deploying application..."

  # Tests de vérification
  verification_tests:
    executor: node/default
    steps:
      - checkout
      - run: echo "Running verification tests..."

  # Tests de validation fonctionnelle
  function_validation_tests:
    executor: node/default
    steps:
      - checkout
      - run: echo "Running functional validation tests..."

  # Tests de charge
  charge_tests:
    executor: node/default
    steps:
      - checkout
      - run: echo "Running load tests..."

  # Déploiement sur l'environnement de développement
  deploy_dev:
    executor: node/default
    steps:
      - checkout
      - run: echo "Deploying to development environment..."

  # Déploiement sur l'environnement de production
  deploy_prod:
    executor: node/default
    steps:
      - checkout
      - run: echo "Deploying to production environment..."

  # Surveillance et suivi
  monitoring:
    executor: node/default
    steps:
      - checkout
      - run: echo "Monitoring..."

# Définition des workflows
workflows:
  version: 2
  build-test-deploy:
    jobs:
      # Exécution des étapes dans l'ordre défini
      - dependencies_install
      - code_analysis
      - cleaning_packaging
      - unit_tests:
          requires:
            - dependencies_install
            - code_analysis
            - cleaning_packaging
      - integration_tests:
          requires:
            - dependencies_install
            - code_analysis
            - cleaning_packaging
      - regression_tests:
          requires:
            - dependencies_install
            - code_analysis
            - cleaning_packaging
      - performance_tests:
          requires:
            - dependencies_install
            - code_analysis
            - cleaning_packaging
      - security_tests:
          requires:
            - dependencies_install
            - code_analysis
            - cleaning_packaging
      - access_tests:
          requires:
            - dependencies_install
            - code_analysis
            - cleaning_packaging
      - preparing_deploying_environment:
          requires:
            - unit_tests
            - integration_tests
            - regression_tests
            - performance_tests
            - security_tests
            - access_tests
      - application_deployment:
          requires:
            - unit_tests
            - integration_tests
            - regression_tests
            - performance_tests
            - security_tests
            - access_tests
      - verification_tests:
          requires:
            - unit_tests
            - integration_tests
            - regression_tests
            - performance_tests
            - security_tests
            - access_tests
      - function_validation_tests:
          requires:
            - unit_tests
            - integration_tests
            - regression_tests
            - performance_tests
            - security_tests
            - access_tests
      - charge_tests:
          requires:
            - unit_tests
            - integration_tests
            - regression_tests
            - performance_tests
            - security_tests
            - access_tests
      - deploy_dev:
          requires:
            - unit_tests
            - integration_tests
            - regression_tests
            - performance_tests
            - security_tests
            - access_tests
      - deploy_prod:
          requires:
            - unit_tests
            - integration_tests
            - regression_tests
            - performance_tests
            - security_tests
            - access_tests
      - monitoring:
          requires:
            - unit_tests
            - integration_tests
            - regression_tests
            - performance_tests
            - security_tests
            - access_tests
