# Configuration du fichier .circleci/config.yml

version: 2.1

# Utilisation des Orbs pour simplifier la configuration
orbs:
  node: circleci/node@5

# Définition des jobs pour les différentes étapes du pipeline
jobs:
  # Installation des dépendances
  install_dependencies:
    executor: node/default
    steps:
      - checkout
      - run: echo "Installing project dependencies..."

  # Analyse du code source
  code_analysis:
    executor: node/default
    steps:
      - checkout
      - run: echo "Performing code analysis..."

  # Nettoyage et packaging de l'application
  clean_and_package:
    executor: node/default
    steps:
      - checkout
      - run: echo "Cleaning and packaging the application..."

  # Tests unitaires
  unit_tests:
    executor: node/default
    steps:
      - checkout
      - run: echo "Running unit tests..."

  # Tests d'intégration
  integration_tests:
    executor: node/default
    steps:
      - checkout
      - run: echo "Running integration tests..."

  # Tests de régression
  regression_tests:
    executor: node/default
    steps:
      - checkout
      - run: echo "Running regression tests..."

  # Tests de performance
  performance_tests:
    executor: node/default
    steps:
      - checkout
      - run: echo "Running performance tests..."

  # Tests de sécurité
  security_tests:
    executor: node/default
    steps:
      - checkout
      - run: echo "Running security tests..."

  # Tests d'accessibilité
  accessibility_tests:
    executor: node/default
    steps:
      - checkout
      - run: echo "Running accessibility tests..."

  # Préparation de l'environnement de déploiement
  prepare_deployment_environment:
    executor: node/default
    steps:
      - checkout
      - run: echo "Preparing deployment environment..."

  # Déploiement de l'application sur l'environnement de développement
  deploy_to_dev:
    executor: node/default
    steps:
      - checkout
      - run: echo "Deploying to development environment..."

  # Déploiement de l'application sur l'environnement de production
  deploy_to_prod:
    executor: node/default
    steps:
      - checkout
      - run: echo "Deploying to production environment..."

  # Surveillance et suivi après déploiement
  monitoring:
    executor: node/default
    steps:
      - checkout
      - run: echo "Monitoring the deployed application..."

# Définition du workflow pour organiser les étapes du pipeline
workflows:
  version: 2
  build-test-deploy:
    jobs:
      # Exécution des étapes dans l'ordre défini
      - install_dependencies
      - code_analysis
      - clean_and_package
      - unit_tests:
          requires:
            - install_dependencies
            - code_analysis
            - clean_and_package
      - integration_tests:
          requires:
            - install_dependencies
            - code_analysis
            - clean_and_package
      - regression_tests:
          requires:
            - install_dependencies
            - code_analysis
            - clean_and_package
      - performance_tests:
          requires:
            - install_dependencies
            - code_analysis
            - clean_and_package
      - security_tests:
          requires:
            - install_dependencies
            - code_analysis
            - clean_and_package
      - accessibility_tests:
          requires:
            - install_dependencies
            - code_analysis
            - clean_and_package
      - prepare_deployment_environment:
          requires:
            - unit_tests
            - integration_tests
            - regression_tests
            - performance_tests
            - security_tests
            - accessibility_tests
      - deploy_to_dev:
          requires:
            - prepare_deployment_environment
      - deploy_to_prod:
          requires:
            - prepare_deployment_environment
      - monitoring:
          requires:
            - deploy_to_dev
            - deploy_to_prod
