version: 2.1

orbs:
  node: circleci/node@5

jobs:

  # Installation des dépendances
  install-deps:
    executor: node/default
    steps:
      - checkout
      - node/install-packages

  # Analyse de code
  analyze-code:
    executor: node/default
    steps:
      - checkout
      - run: npm run lint

  # Build
  build:
    executor: node/default
    steps:
      - checkout
      - run: npm run build

  # Tests unitaires
  test-unit:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run: npm install jest-junit
      - run: npm run test:unit
      - store_test_results:
          path: ./test-results/

  # Tests d'intégration
  test-integration:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run: npm install jest-junit
      - run: npm run test:integration
      - store_test_results:
          path: ./test-results/

  # Déploiement
  deploy:
    executor: node/default
    steps:
      - checkout
      - run: echo "Déploiement de l'application..."

workflows:

  # Build et tests
  build-and-test:
    jobs:
      - install-deps
      - analyze-code
      - build
      - test-unit
      - test-integration

  # Déploiement sur l'environnement de développement
  deploy-dev:
    jobs:
      - build-and-test
      - deploy:
          filters:
            branches:
              only:
                - develop

  # Déploiement sur l'environnement de production
  deploy-prod:
    jobs:
      - build-and-test
      - deploy:
          filters:
            branches:
              only:
                - main

filters:

  # Exclure les branches "feature" et "hotfix" de certains jobs
  exclude-feature-hotfix:
    branches:
      ignore:
        - /^feature.*/
        - /^hotfix.*/
