version: 2.1

orbs:
  node: circleci/node@5

# définition des différents jobs
jobs:
  # installation des dépendances
  installation_dependances:
    executor: node/default
    steps:
      - checkout
      - run: echo "installation des dépendances..."

  # analyse du code
  analyse_code:
    executor: node/default
    steps:
      - checkout
      - run: echo "analyse du code..."

  # nettoyage et empaquetage
  nettoyage_empaquetage:
    executor: node/default
    steps:
      - checkout
      - run: echo "nettoyage et empaquetage..."

  # tests unitaires
  tests_unitaires:
    executor: node/default
    steps:
      - checkout
      - run: echo "exécution des tests unitaires..."

  # tests d'intégration
  tests_integration:
    executor: node/default
    steps:
      - checkout
      - run: echo "exécution des tests d'intégration..."

  # tests de régression
  tests_regression:
    executor: node/default
    steps:
      - checkout
      - run: echo "exécution des tests de régression..."

  # tests de performance
  tests_performance:
    executor: node/default
    steps:
      - checkout
      - run: echo "exécution des tests de performance..."

  # tests de sécurité
  tests_securite:
    executor: node/default
    steps:
      - checkout
      - run: echo "exécution des tests de sécurité..."

  # tests d'accessibilité
  tests_accessibilite:
    executor: node/default
    steps:
      - checkout
      - run: echo "exécution des tests d'accessibilité..."

  # préparation environnement de déploiement
  preparation_deployment:
    executor: node/default
    steps:
      - checkout
      - run: echo "préparation de l'environnement de déploiement..."

  # déploiement de l'application
  deployment_application:
    executor: node/default
    steps:
      - checkout
      - run: echo "déploiement de l'application..."

  # tests de vérification
  tests_verification:
    executor: node/default
    steps:
      - checkout
      - run: echo "exécution des tests de vérification..."

  # tests de validation fonctionnelle
  tests_validation_fonctionnelle:
    executor: node/default
    steps:
      - checkout
      - run: echo "exécution des tests de validation fonctionnelle..."

  # tests de charge
  tests_charge:
    executor: node/default
    steps:
      - checkout
      - run: echo "exécution des tests de charge..."

  # déploiement sur l'environnement de développement
  deployment_dev:
    executor: node/default
    steps:
      - checkout
      - run: echo "déploiement sur l'environnement de développement..."

  # déploiement sur l'environnement de production
  deployment_prod:
    executor: node/default
    steps:
      - checkout
      - run: echo "déploiement sur l'environnement de production..."

  # déploiement sur l'environnement de release
  deployment_release:
    executor: node/default
    steps:
      - checkout
      - run: echo "déploiement sur l'environnement de release..."

  # surveillance et suivi
  surveillance:
    executor: node/default
    steps:
      - checkout
      - run: echo "surveillance..."
# définition des workflows
workflows:
  version: 2
  build-test-deploy:
    jobs:
      - installation_dependances
      - analyse_code
      - nettoyage_empaquetage
      # tests unitaires
      - tests_unitaires:
          requires:
            - installation_dependances
            - analyse_code
            - nettoyage_empaquetage
      # tests d'intégration
      - tests_integration:
          requires:
            - installation_dependances
            - analyse_code
            - nettoyage_empaquetage
          filters:
            branches:
              ignore:
                - /^feature\/.*$/
                - /^hotfix\/.*$/
      # tests de régression
      - tests_regression:
          requires:
            - installation_dependances
            - analyse_code
            - nettoyage_empaquetage
          filters:
            branches:
              ignore:
                - /^feature\/.*$/
                - /^hotfix\/.*$/
      # tests de performance
      - tests_performance:
          requires:
            - installation_dependances
            - analyse_code
            - nettoyage_empaquetage
          filters:
            branches:
              ignore:
                - /^feature\/.*$/
                - /^hotfix\/.*$/
      # tests de sécurité
      - tests_securite:
          requires:
            - installation_dependances
            - analyse_code
            - nettoyage_empaquetage
      # tests d'accessibilité
      - tests_accessibilite:
          requires:
            - installation_dependances
            - analyse_code
            - nettoyage_empaquetage
          filters:
            branches:
              only:
                - master
      # préparation environnement de déploiement
      - preparation_deployment:
          requires:
            - tests_unitaires
            - tests_integration
            - tests_regression
            - tests_performance
            - tests_securite
            - tests_accessibilite
          filters:
            branches:
              ignore:
                - /^feature\/.*$/
                - /^hotfix\/.*$/
      # déploiement de l'application
      - deployment_application:
          requires:
            - tests_unitaires
            - tests_integration
            - tests_regression
            - tests_performance
            - tests_securite
            - tests_accessibilite
          filters:
            branches:
              ignore:
                - /^feature\/.*$/
                - /^hotfix\/.*$/
      # tests de vérification
      - tests_verification:
          requires:
            - tests_unitaires
            - tests_integration
            - tests_regression
            - tests_performance
            - tests_securite
            - tests_accessibilite
          filters:
            branches:
              ignore:
                - /^feature\/.*$/
                - /^hotfix\/.*$/
      # tests de validation fonctionnelle
      - tests_validation_fonctionnelle:
          requires:
            - tests_unitaires
            - tests_integration
            - tests_regression
            - tests_performance
            - tests_securite
            - tests_accessibilite
          filters:
            branches:
              ignore:
                - /^feature\/.*$/
                - /^hotfix\/.*$/
      # tests de charge
      - tests_charge:
          requires:
            - tests_unitaires
            - tests_integration
            - tests_regression
            - tests_performance
            - tests_securite
            - tests_accessibilite
          filters:
            branches:
              ignore:
                - /^feature\/.*$/
                - /^hotfix\/.*$/
      # déploiement sur l'environnement de développement
      - deployment_dev:
          requires:
            - tests_unitaires
            - tests_integration
            - tests_regression
            - tests_performance
            - tests_securite
            - tests_accessibilite
          filters:
            branches:
              only:
                - develop
      # déploiement sur l'environnement de production
      - deployment_prod:
          requires:
            - tests_unitaires
            - tests_integration
            - tests_regression
            - tests_performance
            - tests_securite
            - tests_accessibilite
          filters:
            branches:
              only:
                - master
      # déploiement sur l'environnement de release
      - deployment_release:
          requires:
            - tests_unitaires
            - tests_integration
            - tests_regression
            - tests_performance
            - tests_securite
            - tests_accessibilite
          filters:
            branches:
              only:
                - /^release\/.*$/
      # surveillance et suivi
      - surveillance:
          requires:
            - tests_unitaires
            - tests_integration
            - tests_regression
            - tests_performance
            - tests_securite
            - tests_accessibilite
          filters:
            branches:
              ignore:
                - /^feature\/.*$/
                - /^hotfix\/.*$/
